### ISSUE TITLE
Failed and exited with 1 on TravisCI

### ISSUE THREAD

**Issue by K-Finlay** [rust-lang-deprecated/rustup.sh#72] opened 2016-09-30 07:15 UTC
rustup.sh is currently failing on TravisCI, with no indication as to what the error is.
It has also been reported on the TravisCI bugtracker: [https://github.com/travis-ci/travis-ci/issues/6654](https://github.com/travis-ci/travis-ci/issues/6654)

It may be related to changes made in #71.

Here is the full error message:

> The command "sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=stable -y --disable-sudo 2> /dev/null" failed and exited with 1 during .

**Comment by ninjabear** [comment] 2016-09-30 10:30
For anyone trying to follow the ticket train, it appears this is actually caused by https://github.com/rust-lang/rustup.sh/pull/70

**Comment by ninjabear** [comment] 2016-09-30 10:39
Related https://github.com/rust-lang/rust/issues/36850

**Comment by BanzaiMan** [comment] 2016-09-30 12:12
Hello. As I mentioned in https://github.com/travis-ci/travis-ci/issues/6654#issuecomment-250726019, the issue is that `rustup.sh` can no longer function without `sudo` even when `--disable-sudo` is given.

**Comment by brson** [comment] 2016-09-30 15:06
Fixed by https://github.com/rust-lang/rustup.sh/issues/73 and deploying now. Should be available within 10 minutes. Sorry for the hassle.

**Closed as completed** 2016-09-30 16:03 UTC
